### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by Faizan994** [hin1115/SuperpixelGCN-Segmentation#3]
While running the python uav_preprocessing_sfcn.py file we got the module error: No module named 'models.'. There is no folder in the repo named models, can you please specify it.?

Secondly, all the sub-folders in the "superpixels" folder are empty.

**Comment by HoinJung** [comment]
Please make sure the submodules are correctly copied in the 'superpixels' folder. There should be a submodule 'superfixel_fcn'. That's why the path for the superfixel_fcn is added in the 'uav_preprocessing_sfcn', ```sys.path.append(os.path.abspath('./superpixels/superpixel_fcn'))```. The ```models``` and others are based on the submodule. If the submodule is not available, please manually add superpixelFCN in the preprocessing folder. Here's the address for the superpixel FCN. https://github.com/fuy34/superpixel_fcn.git
